### PR TITLE
Rs management

### PR DESCRIPTION
**Pull request by tlodderstedt**
please review (its about issue #2)

### CODE REVIEW

**Review by panva — APPROVED** [review]

**Comment by tlodderstedt** [comment]
added text for issue #1

**Review by panva — CHANGES_REQUESTED** [review]
`The value of the <spanx style="verb">aud</spanx> claims MUST identify the resource server receiving the token introspection response.`

This sounds like something that removes the actual `aud` of the token, if JWT Introspection is the only way for a RS to introspect how is it going to figure the token being introspected is not meant for it?

**Comment by tlodderstedt** [comment]
We need to prevent replay of the JWT as an access or ID token. I would assume the actual aud is filtered and potentially transformed to identify the individual RS.

What do you typically put into an aud?

**Comment by panva** [comment]
The value of the resource identifier or whatever it derives. I get the why but this takes away the RS option to figure the token is not for it, unless there’s another language introduced that bars jwt introspection responses for tokens not intended for that RS. 

Or we can skip this irs_iat and aud overload nonsense and have the top level all JWT semantics related to the jwt response and the actual regular introspection response in a separate claim like “response”

**Comment by tlodderstedt** [comment]
the aud is supposed to be the resource identifier, so the RS indeed sees whether the token is intended for it. I also added language indicating that the AS must check whether the token is intended for the particular RS.

BTW: you call it nonsense, I call it existing implementations in the field (that do not care about the details of iat) colliding with very detailed IETF review feedback.

**Comment by tlodderstedt** [comment]
how does your implementation determine the resource identifier?

We currently map the scope values to audiences.

**Comment by panva** [comment]
> how does your implementation determine the resource identifier?
> 
> We currently map the scope values to audiences.

The developers provide a mapping function and may take into account the resource parameter(s), scope, ... anything from the request context.

> BTW: you call it nonsense, I call it existing implementations in the field (that do not care about the details of iat) colliding with very detailed IETF review feedback.

Fair enough.

> I also added language indicating that the AS must check whether the token is intended for the particular RS.

This resolves my concern. That being said, i'd rather that the JWT and Introspection Response part gets separated, yes its a breaking change, but one that is warranted by extensive review feedback that took issue with the fact JWT and Introspection responses collide. The IANA registration conflicts would also get somewhat resolved I believe.

**Comment by tlodderstedt** [comment]
I polished the text, added audience restriction as a term and made the text about the aud value more generic again.
re IANA registration: this is about the fact this draft registers OIDC claims not the token metadata
re metadata: as Justin stated correctly, we see this overlay issue all over the place, e.g. also with pushed request objects. That's an heritage of the way JWT mixes metadata and payload. CMS clearly separates them into header value and payload. I accept that as a limitation of the J* stack. Next time we will make it better :-)

**Review by vdzhuvinov — APPROVED** [review]

**Review by vdzhuvinov — APPROVED** [review]

**Comment by vdzhuvinov** [comment]
The resource server management section looks very appropriate and detailed enough. I'm now going through it to improve wording, fix typos, etc.

If I notice something more substantial I'll let you know.

**Comment by tlodderstedt** [comment]
ok. Pls. let me know when I can merge the PR.

**Comment by vdzhuvinov** [comment]
> The jti claim is an identifier for the access token passed in the introspection request.

Do we need this to be a stable identifier? I.e. remaining identical for all introspection calls for a given access token? If so, I can mention this.

**Comment by vdzhuvinov** [comment]
> The authorization server will set the value of the response claim active to false. Otherwise, this claim is set to true.

Should we say say MUST? We have pretty strong normative language about the remaining claims.

Also, noticed that the text is not consistent on "draft" (11 words) and "specification" (15). I can quickly fix this.

**Comment by tlodderstedt** [comment]
> > The jti claim is an identifier for the access token passed in the introspection request.
> 
> Do we need this to be a stable identifier? I.e. remaining identical for all introspection calls for a given access token? If so, I can mention this.

Added requirement "This identifier MUST be stable for all introspection calls for a given access token."

> > The authorization server will set the value of the response claim active to false. Otherwise, this claim is set to true.
> 
> Should we say say MUST? We have pretty strong normative language about the remaining claims.

done

> Also, noticed that the text is not consistent on "draft" (11 words) and "specification" (15). I can quickly fix this.

fixed (several draft(s) where located in comments and metadata

**Pull request merged**
